parameters:
    # Adds a fallback OAUTH2_URL if the env var is not set.
  env(OAUTH_URL): 'https://openid.manuele-vaccari.ch'

twig:
    globals:
        oauth_url: '%env(OAUTH_URL)%'

knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        # will create service: "knpu.oauth2.client.orbitrondev"
        # an instance of: KnpU\OAuth2ClientBundle\Client\OAuth2Client
        generation2:
            type: generic
            provider_class: D3strukt0r\OAuth2\Client\Provider\OpenIDProvider

            # optional: a class that extends OAuth2Client
            # client_class: Some\Custom\Client

            # optional: if your provider has custom constructor options
            provider_options:
                host: '%env(OAUTH_URL)%'

            # now, all the normal options!
            client_id: '%env(OAUTH_CLIENT_ID)%'
            client_secret: '%env(OAUTH_CLIENT_SECRET)%'
            redirect_route: login_check
            redirect_params: {}
